### ISSUE TITLE
Robot just moves forward and backward

### ISSUE THREAD

**Issue by emfolkerts** [InfinitiesLoop/oclib#2]
Hello, I am trying to understand how to get the robot to build. I'm using the build in provingground.model file to learn the setup.
I have moved the chest around as well as the charger and nothing seems to work the robot just seems to keep moving 6 blocks forward and then immediately 6 blocks backward. Here is what the robot says. The robot also has a Diamond Pickaxe in its inventory.

Charging... 
I'm off to build stuff, wish me luck!
Starting at level 1 at (1,1)
Oh no! Couldn't follow path to build site: could not ensure adjacent spot was clear at (2,1): Lost durability on tool and can't find a fresh one in my Inventory! 
Headed home from level 1 at (1,1).
Then repeat.

I feel I should mention I am on a superflat world and am using the creatix robot.

**Comment by InfinitiesLoop** [comment]
Thanks for checking it out!

Make sure the tool is in the Robot's tool slot, not just in its inventory. It will select from it's inventory when the tool breaks, but it needs to have an actual starting tool in the tool slow so it knows which tool to look for.

**Comment by BlindCameraMan** [comment]
That did it! Thank you!
